language: php

php:
  - 7.1

services:
  - mysql

before_script:
  - composer self-update

before_install:
  - mysql -e 'CREATE DATABASE test_fixture;'

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - bin/phpunit -v
